- name: detect rvm installed
  stat: path=~/.rvm
  register: rvm_installed

- name: install public key
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  when: rvm_installed.stat.exists == false

- name: install rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable
  when: rvm_installed.stat.exists == false

- name: install ruby
  shell: ~/.rvm/bin/rvm install {{ ruby_version }}

- name: set default version of ruby with rvm
  shell: ~/.rvm/bin/rvm --default use {{ ruby_version }}
