- name: upgrade all packages
  yum: name=* state=latest
  sudo: yes

- name: install git
  yum: name=git
  sudo: yes

- name: set forward root email
  lineinfile: "dest=/etc/aliases line='root: {{ email }}'"
  sudo: yes
  notify: rebuild aliases

- name: set timezone /etc/sysconfig/clock
  lineinfile: dest=/etc/sysconfig/clock regexp='^ZONE=' line='ZONE="Asia/Tokyo"'
  sudo: yes

- name: set timezone /etc/localtime
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=true
  sudo: yes

- name: set hostname /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127.0.0.1 ' line='127.0.0.1 {{ hostname }} localhost localhost.localdomain'
  sudo: yes

- name: set hostname /etc/sysconfig/network
  lineinfile: dest=/etc/sysconfig/network regexp='^HOSTNAME=' line='HOSTNAME={{ hostname }}'
  sudo: yes
